version: "3.9"
services:
# nginx
  nginx:
    container_name: nginx
    hostname: nginx
    working_dir: /var/www/sites/
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d:rw
      - ./sites:/var/www/sites
# php
  php:
    container_name: php
    hostname: php-fpm
    build:
      context: .
      dockerfile: php-fpm/Dockerfile
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - ./sites:/var/www/sites
    working_dir: /var/www/sites/
# Networks
networks:
  app-network:
    driver: bridge