version: "3.9"
services:
# nginx
  nginx:
    container_name: nginx
    hostname: nginx
    working_dir: /var/www/sites/
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d:rw
      - ./sites:/var/www/sites
# php
  php:
    container_name: php
    hostname: php-fpm
    build:
      context: .
      dockerfile: php-fpm/Dockerfile
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - ./sites:/var/www/sites
    working_dir: /var/www/sites/
# postgresql
  postgres:
    container_name: pg
    hostname: postgres
    build:
      context: .
      dockerfile: postgres/Dockerfile
    env_file:
      - ./postgres/postgres.env
    networks:
      - app-network
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/backup:/opt/backups
# pgadmin
  pgadmin:
      container_name: pgadmin
      hostname: pgadmin
      build:
        context: ./pgadmin
        dockerfile: Dockerfile
      depends_on:
        - postgres
      env_file:
        - ./pgadmin/.env
      networks:
        - app-network
      ports:        
        - "8081:80"
      restart: always
      volumes:
        - pgadmin_data:/var/lib/pgadmin
# Networks
networks:
  app-network:
    driver: bridge
volumes:
  postgres_data:
  pgadmin_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./pgadmin/data